name: regente

services:
  postgres:
    image: postgres:16
    container_name: regente-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: regente
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: regente-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - postgres

  backend:
    build: ./backend
    container_name: regente-backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://root:root@postgres:5432/regente
      - PORT=3000
      - JWT_SECRET=supersecreto123
      
  frontend:
    build: ./frontend
    container_name: regente-frontend
    restart: always
    ports:
      - "4321:4321"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

volumes:
  pgdata:
